#!/bin/bash

set -e -E -u -o pipefail -o noclobber -o noglob +o braceexpand || exit 1
trap 'printf "[ee] failed: %s\n" "${BASH_COMMAND}" >&2' ERR || exit 1

exec </dev/null >&2

MODACLOUDS_MONITORING_MANAGER_HOME='@{package:root}'
MANAGER_HOME='@{definitions:environment:MANAGER_HOME}'
MANAGER_CONF='@{definitions:environment:MANAGER_CONF}'
JAVA_HOME='@{definitions:environment:JAVA_HOME}'

test -n "${MODACLOUDS_MONITORING_MANAGER_ENDPOINT_IP}"
test -n "${MODACLOUDS_MONITORING_MANAGER_ENDPOINT_PORT}"

test -n "${MODACLOUDS_MONITORING_DDA_ENDPOINT_IP}"
test -n "${MODACLOUDS_MONITORING_DDA_ENDPOINT_PORT}"

test -n "${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_IP}"
test -n "${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_PORT}"

test -n "${MODACLOUDS_MONITORING_SDA_WEKA_ENDPOINT_IP}"
test -n "${MODACLOUDS_MONITORING_SDA_WEKA_ENDPOINT_PORT}"

test -n "${MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_IP}"
test -n "${MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_PORT}"

export JAVA_HOME
export PATH="${JAVA_HOME}/bin:${PATH}"

cd -- "${MANAGER_HOME}"

cat \
	>|"${MANAGER_CONF}/monitoring_manager.properties" \
	<<EOS
mm_server.port=${MODACLOUDS_MONITORING_MANAGER_ENDPOINT_PORT}
mm_server.address=${MODACLOUDS_MONITORING_MANAGER_ENDPOINT_PORT}
dda_server.port=${MODACLOUDS_MONITORING_DDA_ENDPOINT_PORT}
dda_server.address=${MODACLOUDS_MONITORING_DDA_ENDPOINT_IP}
matlab_sda_server.port=${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_PORT}
matlab_sda_server.address=${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_IP}
java_sda_server.port=${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_PORT}
java_sda_server.address=${MODACLOUDS_MONITORING_SDA_MATLAB_ENDPOINT_IP}
EOS

cat \
	>|"${MANAGER_CONF}/kb.properties" \
	<<EOS
kb_server.port=${MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_PORT}
kb_server.address=${MODACLOUDS_KNOWLEDGEBASE_ENDPOINT_IP}
EOS

exec java -jar ./main.jar

exit 1
